### ISSUE TITLE
Execution workflow: RNAseq_PAS_finder

### ISSUE THREAD

**Issue by faricazjj** [iRNA-COSI/APAeval#266]
As of June 23, 2022, the github page is not ready. The author is still working on the github page so this tool is blocked until then.

preprint: https://www.biorxiv.org/content/10.1101/2022.05.27.493724v1.full
github page: https://github.com/mashlosenok/RNAseq_PAS_finder

## Child issues
Proof of concept: https://github.com/iRNA-COSI/APAeval/issues/267
Implementation:https://github.com/iRNA-COSI/APAeval/issues/273
Testing & review: https://github.com/iRNA-COSI/APAeval/issues/275

## WHAT    
**Write** execution workflow for [InPAS](http://www.bioconductor.org/packages/release/bioc/vignettes/InPAS/inst/doc/InPAS.html). Use the provided [small files for testing](https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data) (running the workflow on real data is a different issue).

## CHECKLIST   
* [ ] Use [snakemake template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/snakemake) or [nextflow template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/nextflow) to create your workflow.
* [ ] Comment your code
* [ ] Run individual rules/processes in either conda envs or docker/singularity containers for reproducibility
* [] Input:  .bam or .fastq from [test_data]((https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data))
* [] Give [feedback about the method](https://forms.gle/mAAkbRJqhedJnSeJ6)

## OUTPUTS (see [specification](https://github.com/iRNA-COSI/APAeval/blob/main/execution_workflows/execution_output_specification.md)): 
* [ ] Output: Adhere to output specification for Identification challenge
     > This BED file contains single-nucleotide position of poly(A) sites identified by the tool.
Fields:

    > chrom - the name of the chromosome
    chromStart - the starting position of the feature in the chromosome
    chromEnd - the ending position of the feature in the chromosome; as identified PAS are single-nucleotide, the ending position is the same as starting position
    name - defines the name of the identified poly(A) site
    score - not used, leave as "."
    strand - defines the strand; either "." (=no strand) or "+" or "-".

* [ ] Output: Adhere to output specification for quantification challenge
     > This BED file contains positions of unique poly(A) sites with TPM values for each identified site in the score column.

    > chrom - the name of the chromosome
    chromStart - the starting position of the feature in the chromosome
    chromEnd - the ending position of the feature in the chromosome; as identified PAS are single-nucleotide, the ending position is the same as starting position
    name - defines the name of the identified poly(A) site
    score - TPM value for the identified site
    strand - defines the strand; either "." (=no strand) or "+" or "-".

* [ ] Output: Adhere to output specification for differential usage challenge
   > This TSV file contains two columns:

    > - gene ID
    > - significance of differential PAS usage

    > Column names should not be added to the file.

**Comment by mrgazzara** [comment]
As discussed with Sam and Yue Kei, we feel like this is unlikely to be assigned. Like AltTSSPAS, there is no publication associated with this (only a [slideshow presentation](https://www.researchgate.net/publication/344404962_De_novo_identification_of_polyadenylation_sites_from_RNA-seq_data)) and the tool is more of a wrapper that would require us to apply a number of heuristics / filtering steps to go from raw reads counts output by the scripts to TPM or relative quantifications. The [repo](https://github.com/mashlosenok/RNAseq_PAS_finder) has not been updated in 13 months. We may want to contact the authors and inquire further if we want to be thorough.

**Comment by faricazjj** [comment]
Emailed the author to confirm that the tool has no publication associated with it. Will close this issue once author replies or by June 28, whichever is sooner.

**Comment by faricazjj** [comment]
The author replied with a link to the preprint, but the github page is currently not yet updated with instructions on how to run. We'll move this to low priority until the author gets back with the updated github page. I'll add the links in the description of this issue!

**Comment by faricazjj** [comment]
Emailed the author for updates on the github page. But as of today (July 27th, 2022) the github page of this tool is not ready, there are no instructions on how to run the tool. Closing all RNAseq_PAS_finder related issues.
