### ISSUE TITLE
Scientific manuscript: complete manuscript content

### ISSUE THREAD

**Issue by faricazjj** [iRNA-COSI/APAeval#285]
- [ ] Finalize abstract section #319 (partially blocked by #317)
- [ ] Finalize introduction section #320
- [ ] Finalize methods section #318
- [ ] Draft and finalize results section #317
- [ ] Finalize discussion section #321 (partially blocked by #317)
- [ ] Generate figures and figure legends #322 (partially blocked by #317)
- [ ] Draft and finalize supplemental figures, tables, and methods #323 (partially blocked by #317)
- [ ] Finalize authors, institutions, and acknowledgements #310
- [ ] Proofread and finalize manuscript for submission #312, #314, #315
