### ISSUE TITLE
Scientific manuscript: prepare for submission

### ISSUE THREAD

**Issue by faricazjj** [iRNA-COSI/APAeval#286]
- [x] Update the list of authors and institutions [#310](#310) 
- [x] Where will we submit the manuscript? (Current plan is RNA) [#311](#311)
- [x] What are the author instructions for submission? (Word count, number of figures, tables, etc) [#311](#311)
- [x] Does the journal have a template for submission? [#311](#311)
- [x] Have all authors read and commented on the manuscript? [#312](#312)
- [x] Have all authors agreed to the final version of the manuscript? [#312](#312)
- [ ] Has all code been uploaded to the APAeval Github repository? [#313](#313)
- [x] Have all references been added to the manuscript and unlinked from Zotero? [#314](#314)
- [x] Are all text and figure documents converted to PDF format? [#315](#315)
- [x] Submit the manuscript to biorxiv; ask biorxiv to simultaneously submit to the journal on our behalf [#316](#316)
