### ISSUE TITLE
Scientific Manuscript Writing: Supplemental Information

### ISSUE THREAD

**Issue by FitzsimmonsCM** [iRNA-COSI/APAeval#323]
- [ ] Draft supplemental methods (related to [#318](#318))
- [ ] Draft supplemental figures and figure legends (related to [#322](#322))
- [ ] Draft supplemental data and tables (related to [#317](#317))
